type: object
properties:
  resourceType:
    type: string
    example: Parameters
  parameter:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
          example: passedPrescriptions
        resource:
          type: object
          properties:
            resourceType:
              type: string
              example: Bundle
            id:
              type: string
              example: 155e1102-9e71-4f19-9453-b905c0bbc494
            meta:
              type: object
              properties:
                lastUpdated:
                  type: string
                  format: date-time
                  example: 2021-07-15T11:25:25+00:00
            identifier:
              type: object
              properties:
                system:
                  type: string
                  example: https://tools.ietf.org/html/rfc4122
                value:
                  type: string
                  example: 53aa80e7-7ccb-485e-b544-214bba1334a9
            type:
              type: string
              example: searchset
            total:
              type: integer
              format: int32
              example: 1
            entry:
              type: array
              items:
                type: object
                properties:
                  resource:
                    type: object
                    properties:
                      resourceType:
                        type: string
                        example: Bundle
                      id:
                        type: string
                        example: 67ca2830-4934-41ad-95d0-f31d9f8b61fb
                      meta:
                        type: object
                        properties:
                          lastUpdated:
                            type: string
                            format: date-time
                            example: 2021-07-15T11:24:43+00:00
                      identifier:
                        type: object
                        properties:
                          system:
                            type: string
                            example: https://tools.ietf.org/html/rfc4122
                          value:
                            type: string
                            example: ed4a6ba4-ef83-47d4-aa48-6c7fb437905e
                      type:
                        type: string
                        example: message
                      entry:
                        type: array
                        items:
                          type: object
                          properties:
                            resource:
                              type: object
                              properties:
                                resourceType:
                                  type: string
                                  example: MessageHeader
                                id:
                                  type: string
                                  example: 2e48528f-1fc6-4fd1-9f9e-c400980e7f2b
                                extension:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      url:
                                        type: string
                                        example: https://fhir.nhs.uk/StructureDefinition/Extension-Spine-MessageHeader-messageId
                                      valueIdentifier:
                                        type: object
                                        properties:
                                          system:
                                            type: string
                                            example: https://tools.ietf.org/html/rfc4122
                                          value:
                                            type: string
                                            example: ed4a6ba4-ef83-47d4-aa48-6c7fb437905e
                                eventCoding:
                                  type: object
                                  properties:
                                    system:
                                      type: string
                                      example: https://fhir.nhs.uk/CodeSystem/message-event
                                    code:
                                      type: string
                                      example: prescription-order
                                    display:
                                      type: string
                                      example: Prescription Order
                                destination:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      endpoint:
                                        type: string
                                        example: urn:nhs-uk:addressing:ods:FH542
                                      receiver:
                                        type: object
                                        properties:
                                          identifier:
                                            type: object
                                            properties:
                                              system:
                                                type: string
                                                example: https://fhir.nhs.uk/Id/ods-organization-code
                                              value:
                                                type: string
                                                example: FH542
                                sender:
                                  type: object
                                  properties:
                                    identifier:
                                      type: object
                                      properties:
                                        system:
                                          type: string
                                          example: https://fhir.nhs.uk/Id/ods-organization-code
                                        value:
                                          type: string
                                          example: X2601
                                    display:
                                      type: string
                                      example: NHS Digital Spine
                                source:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: NHS Spine
                                    endpoint:
                                      type: string
                                      example: https://int.api.service.nhs.uk/electronic-prescriptions/$process-message
                                response:
                                  type: object
                                  properties:
                                    identifier:
                                      type: string
                                      example: 9a14ee11-9f58-4d67-8988-2220cd99bd29
                                    code:
                                      type: string
                                      example: ok
                                focus:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      reference:
                                        type: string
                                        example: urn:uuid:df12b683-483c-486e-a9ef-213f915c997b
                            fullUrl:
                              type: string
                              example: urn:uuid:2e48528f-1fc6-4fd1-9f9e-c400980e7f2b
                  fullUrl:
                    type: string
                    example: urn:uuid:67ca2830-4934-41ad-95d0-f31d9f8b61fb
