version: '3'
services:
  swagger-editor:
    image: 'swaggerapi/swagger-editor'
    container_name: 'eps-swagger-editor'
    build:
      context: .
    environment:
      - SWAGGER_FILE=/tmp/electronic-prescription-service-api.yaml
      # - SWAGGER_FILE=/tmp/dist/electronic-prescription-service-api.resolved.json
    ports:
      - "5000:8080"
    volumes:
      - .:/tmp
