name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "Electronic-Prescription-Service-Build"
      trigger:
        branches:
          include:
            - refs/tags/v*

pool:
  name: "AWS-ECS"

variables:
  - template: project.yml
  - group: pact
  - group: eps-ref-smoke-tests
  - group: eps-smoke-tests

extends:
  template: azure-release-template.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    enable_monitoring: true
    enable_status_monitoring: true
    manual_approval_env: manual-approval-ptl
    jinja_templates:
      REQUIRE_ASID: false
    apigee_deployments:
      - environment: manual-approval
        stage_name: manual_approval_qa
        depends_on: []
      - environment: manual-approval
        stage_name: manual_approval_ref
        depends_on: []
      - environment: manual-approval
        stage_name: manual_approval_external_ptl
        depends_on: []
      - environment: manual-approval
        stage_name: manual_approval_prod
        depends_on: []
      - environment: internal-dev
        proxy_path: live
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      - environment: internal-qa
        proxy_path: live
        depends_on:
          - internal_dev
          - manual_approval_qa
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      - environment: ref
        proxy_path: live
        depends_on:
          - int
          - manual_approval_ref
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      - environment: sandbox
        proxy_path: sandbox
        depends_on:
          - manual_approval_external_ptl
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      - environment: int
        proxy_path: live
        depends_on:
          - manual_approval_external_ptl
        secret_file_ids:
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_certificate.crt
          - ptl/api-deployment/electronic-prescription-api/int/eps_int_test_private.key
      - environment: prod
        proxy_path: live
        depends_on:
          - int
          - manual_approval_prod
        jinja_templates:
          REQUIRE_ASID: true
