name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ["*"]

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    cache_steps:
      - task: DownloadGitHubRelease@0
        displayName: Download Validator
        inputs:
          connection: NHSDigital
          userRepository: NHSDigital/validation-service-fhir-r4
          itemPattern: "**"
          defaultVersionType: specificTag
          version: v1.0.112-alpha
          downloadPath: "validator"
      - task: NodeTool@0
        displayName: Use Node v16.14.x
        inputs:
          versionSpec: "16.14.2"
      - bash: "make prepare-for-api-release"
        displayName: Prepare for api release
        workingDirectory: "${{ variables.service_name }}"
      - bash: "make install-java"
        displayName: "Install JDK & JRE for schema validation"
        workingDirectory: "${{ variables.service_name }}"
    test_steps:
      - bash: "make check-language-versions"
        displayName: Check consistent language version
        workingDirectory: "${{ variables.service_name }}"
      - bash: "make test"
        displayName: Run Quality Checks
        workingDirectory: "${{ variables.service_name }}"
      - task: PublishTestResults@2
        displayName: "Publish Test Results"
        inputs:
          testResultsFormat: "JUnit"
          testResultsFiles: "**/junit.xml"
          searchFolder: "${{ variables.service_name }}"
          mergeTestResults: true
          testRunTitle: "EPS Tests"
          failTaskOnFailedTests: true
