name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Electronic-Prescription-Service-Build"
    trigger:
      branches:
        exclude:
          - master
          - refs/heads/master
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml
  - group: pact
  - group: eps-temp

extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    apigee_deployments:
      - environment: internal-dev-sandbox
        proxy_path: sandbox
      - environment: internal-dev
        proxy_path: live
        depends_on:
          - internal_dev_sandbox
    post_deploy: 
      - task: DockerInstaller@0
        displayName: Docker Installer
        inputs:
          dockerVersion: 17.09.0-ce
          releaseType: stable
      - task: Bash@3
        inputs:
          targetType: 'filePath'
          filePath: smoke_tests.sh
        workingDirectory: ${{ variables.service_name }}/$(SERVICE_ARTIFACT_NAME)
        displayName: Run Smoke Tests
