name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
    - pipeline: build_pipeline
      source: "Electronic-Prescription-Service-Build"
      trigger:
        branches:
          include:
            - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml
  - group: pact
  - group: eps-ref-smoke-tests

extends:
  template: azure-release-template.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    service_base_path_pr: none
    spec_file: ${{ variables.spec_file }}
    enable_monitoring: true
    enable_status_monitoring: false
    jinja_templates:
        REQUIRE_ASID: false
    apigee_deployments:
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        make_spec_visible: true
      - environment: internal-dev
        proxy_path: live
        make_spec_visible: true
#      - environment: int
#        stage_name: int-preview
#        make_spec_visible: true
#        fully_qualified_service_name: electronic-prescription-service-api-int-preview
#        service_base_path: electronic-prescriptions-preview
#        service_name: electronic-prescription-service-api-int-preview
#        short_service_name: eps-coordinator-preview
#        product_display_name: Electronic Prescription Service (Preview)
#        proxy_path: live
#        depends_on:
#            - internal_dev
#            - internal_dev_sandbox
      - environment: dev
        make_spec_visible: false
        proxy_path: live
      - environment: sandbox
        proxy_path: sandbox
        depends_on:
          - manual_approval
      - environment: int
        make_spec_visible: true
        proxy_path: live
        depends_on:
          - manual_approval
      - environment: ref
        proxy_path: live
        depends_on:
          - int
          - sandbox
          - manual_approval
      - environment: prod
        # todo: make_spec_visible: true when ready for live
        make_spec_visible: false
        proxy_path: live
        depends_on:
          - int
          - sandbox
          - manual_approval
        jinja_templates:
            REQUIRE_ASID: true
