name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Electronic-Prescription-Service-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  vmImage: 'ubuntu-latest'

variables:
  - template: project.yml
  - group: pact
  - group: eps-ref-smoke-tests

extends:
  template: azure-release-template.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    product_display_name: ${{ variables.product_display_name }}
    product_description: ${{ variables.product_description }}
    service_base_path_pr: none
    spec_file: ${{ variables.spec_file }}
    enable_monitoring: true
    apigee_deployments:
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        make_spec_visible: true
      - environment: internal-dev
        proxy_path: live
        make_spec_visible: true
      - environment: internal-qa-sandbox
        proxy_path: sandbox
        make_spec_visible: true
        depends_on:
          - internal_dev
          - internal_dev_sandbox
      - environment: internal-qa
        proxy_path: live
        make_spec_visible: true
        depends_on:
          - internal_dev
          - internal_dev_sandbox
