[project]
python = "^3.8"

[tool.poetry]
name = "electronic-prescription-service-api"
version = "0.0.1-alpha"
description = "Electronic Prescription Service API Definitions"
license = "MIT"
authors = [
    "Alex McCormick <alex.mccormick1@nhs.net>",
    "Callum Tipper <callum.tipper1@nhs.net>",
    "Conner Jowitt <conner.jowitt1@nhs.net>",
    "Dan Jones <dan.jones13@nhs.net>",
    "Harry Coulter <harry.coulter1@nhs.net>",
    "Matt Jarvis <matt.jarvis1@nhs.net>",
    "Richard Crawley <richard.crawley1@nhs.net>",
    "Mukhtar Abdul Ghani <mukhtar.abdulghani1@nhs.net>",
    "Chris Lopez <>",
    "Tom Smith <>",
    "Jack Robinson <jack.robinson4@nhs.net>"
]
readme = "README.md"
repository = "https://github.com/NHSDigital/electronic-prescription-service-api"

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^6.0"
docopt = "^0.6.2"
jsonpath-rw = "^1.4.0"
semver = "^3.0.2"
gitpython = "^3.1.40"
pytest = "^7.4.3"
requests = "^2.31.0"
boto3 = "^1.33.2"
argparse = "^1.4.0"
atlassian-python-api = "^3.41.3"
pre-commit = "^3.5.0"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
black = "^23.11"
pip-licenses = "^4.3.3"
jinja2 = "^3.1.2"

[tool.poetry.scripts]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
