AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Main template for Load Balancer

Parameters:
  StackName:
    Type: String
    Default: none

  EnableMutualTLS:
    Type: String
    Default: false

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for the load balancer

  VPC:
    Type: AWS::EC2::VPC::Id

  SubnetA:
    Type: AWS::EC2::Subnet::Id

  SubnetB:
    Type: AWS::EC2::Subnet::Id

  HostedZoneName:
    Type: String
    Default: company.com

  Subdomain:
    Type: String
    Default: myservice

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

Resources:
  LoadBalancerResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: load_balancer_resources.yaml
      Parameters:
        CertificateArn: !Ref CertificateArn
        VPC: !Ref VPC
        SubnetA: !Ref SubnetA
        SubnetB: !Ref SubnetB
        HostedZoneName: !Ref HostedZoneName
        Subdomain: !Ref Subdomain

Outputs:
  Endpoint:
    Description: Load Balancer Endpoint
    Value: !GetAtt LoadBalancerResources.Outputs.Endpoint
