AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Main template for Load Balancer

Parameters:
  StackName:
    Type: String
    Default: none

  EnableMutualTLS:
    Type: String
    Default: false

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  VPC:
    Type: AWS::EC2::VPC::Id
    Default: "vpc-0f97ef05d582e50dc"

  SubnetA:
    Type: AWS::EC2::Subnet::Id
    Default: "subnet-081d80544dd3be7a0"

  SubnetB:
    Type: AWS::EC2::Subnet::Id
    Default: "subnet-05db1befe34d2ad4f"

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

  DomainNameExport:
    Type: String
    Description: The domain name to be used for the certificate
    Default: "pfp.dev.eps.national.nhs.uk"

  ZoneIDExport:
    Type: String
    Description: The hosted zone ID for the domain

Resources:
  GenerateCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      ValidationMethod: DNS
      DomainName: !Ref DomainNameExport
      DomainValidationOptions:
        - DomainName: !Ref DomainNameExport
          HostedZoneId: !Ref ZoneIDExport

  LoadBalancerResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: load_balancer_resources.yaml
      Parameters:
        CertificateArn: !Sub "arn:aws:acm:${AWS::Region}:${AWS::AccountId}:certificate/a414c6a6-4ecb-4071-96f0-7de2e5a95413"
        VPC: !Ref VPC
        SubnetA: !Ref SubnetA
        SubnetB: !Ref SubnetB
        HostedZoneName: !Ref DomainNameExport
        Subdomain: !Ref StackName

Outputs:
  Endpoint:
    Description: Load Balancer Endpoint
    Value: !GetAtt LoadBalancerResources.Outputs.Endpoint
