AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Main template for Load Balancer with all resources included

Parameters:
  StackName:
    Type: String

  EnableMutualTLS:
    Type: String
    Default: false

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  VPC:
    Type: AWS::EC2::VPC::Id

  SubnetA:
    Type: AWS::EC2::Subnet::Id

  SubnetB:
    Type: AWS::EC2::Subnet::Id

  SubnetC:
    Type: AWS::EC2::Subnet::Id

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

  DomainNameExport:
    Type: String
    Description: The domain name to be used for the certificate
    Default: dev.eps.national.nhs.uk

  ZoneIDExport:
    Type: String
    Description: The hosted zone ID for the domain
    Default: Z0135802PDMHNUI5JMQ7

  HostedZoneName:
    Type: String
    Default: company.com

  Subdomain:
    Type: String
    Default: myservice

Resources:
  GenerateCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      ValidationMethod: DNS
      DomainName:
        Fn::Join:
          - .
          - - !Ref Subdomain
            - !Ref HostedZoneName
      DomainValidationOptions:
        - DomainName: !Join
            - .
            - - !Ref Subdomain
              - !Ref HostedZoneName
          HostedZoneId: !Ref ZoneIDExport

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Name: !Sub '${AWS::StackName}-LoadBalancer'
      Scheme: internet-facing
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
        - !Ref SubnetC

  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: authenticate-cognito
          AuthenticateCognitoConfig:
            UserPoolArn: !GetAtt CognitoUserPool.Arn
            UserPoolClientId: !Ref CognitoUserPoolClient
            UserPoolDomain: !Ref CognitoUserPoolDomain
            AuthenticationRequestExtraParams:
              Param1: "value1"
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref GenerateCertificate
      SslPolicy: ELBSecurityPolicy-2016-08

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Sub '${AWS::StackName}-TargetGroup'
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      TargetType: ip
      VpcId: !Ref VPC

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${HostedZoneName}.'
      Name: !Sub '${Subdomain}.${HostedZoneName}'
      Type: A
      AliasTarget:
        DNSName: !Ref DomainNameExport
        HostedZoneId: !Ref ZoneIDExport

Outputs:
  Endpoint:
    Description: Load Balancer Endpoint
    Value: !Sub 'https://${Subdomain}.${HostedZoneName}'
