AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  Main template for Load Balancer with all resources included, supporting mutual TLS

Parameters:
  StackName:
    Type: String

  EnableMutualTLS:
    Type: String

  TruststoreVersion:
    Type: String

  TruststoreFile:
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id

  SubnetA:
    Type: AWS::EC2::Subnet::Id

  SubnetB:
    Type: AWS::EC2::Subnet::Id

  SubnetC:
    Type: AWS::EC2::Subnet::Id

  VersionNumber:
    Type: String

  CommitId:
    Type: String

  HostedZoneName:
    Type: String

Conditions:
  CreateTruststore: !Equals [!Ref EnableMutualTLS, true]
  CreateListenerHTTPS: !Equals [!Ref EnableMutualTLS, true]

Resources:
  # Generate a new ACM certificate
  GenerateCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      ValidationMethod: DNS
      DomainName:
        Fn::Join:
          - "."
          - - !Ref StackName
            - !ImportValue eps-route53-resources:EPS-domain
      DomainValidationOptions:
        - DomainName:
            Fn::Join:
              - "."
              - - !Ref StackName
                - !ImportValue eps-route53-resources:EPS-domain
          HostedZoneId: !ImportValue eps-route53-resources:EPS-ZoneID

  # Create a new Application Load Balancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Scheme: internet-facing
      SecurityGroups:
        - !ImportValue vpc-resources:VpcDefaultSecurityGroup
      Subnets:
        - !Ref SubnetA
        - !Ref SubnetB
        - !Ref SubnetC

  # Create Trust Store for mTLS
  Truststore:
    Type: AWS::ElasticLoadBalancingV2::TrustStore
    Condition: CreateTruststore
    Properties:
      CaCertificatesBundleS3Bucket: "ci-resources-truststorebucket-1emm0xo65wil5"
      CaCertificatesBundleS3Key: "fhirfacade-truststore.pem"
      Name: !Sub "${StackName}-trst"

  # Create Listener with mTLS Verify Mode
  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Condition: CreateListenerHTTPS
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref GenerateCertificate
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      MutualAuthentication:
        Mode: verify
        TrustStoreArn: !If
          - CreateTruststore
          - !GetAtt Truststore.TrustStoreArn
          - !Ref "AWS::NoValue"

  # Create Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 60
      TargetType: ip
      VpcId: !Ref VPC

  # DNS Record for Load Balancer
  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !ImportValue eps-route53-resources:EPS-ZoneID
      Name: !Join
        - "."
        - - !Ref StackName
          - !ImportValue eps-route53-resources:EPS-domain
      Type: A
      AliasTarget:
        DNSName: !GetAtt LoadBalancer.DNSName
        EvaluateTargetHealth: False
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID

Outputs:
  Endpoint:
    Description: Load Balancer Endpoint
    Value: !Sub 'https://${StackName}.${HostedZoneName}'
