name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "EPS-API-Tool-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

extends:
  template: azure-release-template.yml
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    manual_approval_env: manual-approval-ptl
    apigee_deployments:
      - environment: manual-approval
        stage_name: manual_approval_qa
        depends_on: []
      - environment: manual-approval
        stage_name: manual_approval_sandbox
        depends_on: []
      - environment: manual-approval
        stage_name: manual_approval_int
      - environment: internal-dev
        depends_on: []
      - environment: internal-dev-sandbox
        proxy_path: sandbox
        depends_on: []
      - environment: internal-qa
        depends_on:
          - manual_approval_qa
      - environment: sandbox
        proxy_path: sandbox
        depends_on:
          - manual_approval_sandbox
      - environment: int
        proxy_path: live
        depends_on:
          - manual_approval_int
