version: '3'
services:
    eps-api-tool:
        image: 'eps-api-tool-local'
        build:
            context: site
            dockerfile: Dockerfile-Site
        environment:
            - PYTHONUNBUFFERED=1
            - FLASK_ENV=development
            - FLASK_RUN_PORT=9000
            - DEV_MODE=True
            - ENVIRONMENT=internal-dev-sandbox
            - SESSION_TOKEN_ENCRYPTION_KEY=ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=
            - HAPI_URL=http://eps-api-tool-hapi:9001
            - PUBLIC_APIGEE_URL=http://localhost:9010
            - APIGEE_DOMAIN_NAME=internal-dev-sandbox.api.service.nhs.uk
        ports:
            - "9010:9000"
        volumes:
            - ./site/client-react/dist/index.js:/app/static/index.js
            - ../examples:/app/static/examples
    eps-api-tool-hapi:
        image: 'eps-api-tool-hapi-local'
        build:
            context: site
            dockerfile: Dockerfile-Hapi
        environment:
            - ENVIRONMENT=internal-dev-sandbox
            - SESSION_TOKEN_ENCRYPTION_KEY=ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=
            - PUBLIC_APIGEE_URL=http://localhost:9010
            - APIGEE_DOMAIN_NAME=internal-dev-sandbox.api.service.nhs.uk
            # Uncomment to skip validation in EPS
            #- EPS_SKIP_VALIDATION=1
            # Uncomment to use local EPS (overrides other config)
            #- EPS_URL=http://host.docker.internal:9000/FHIR/R4
            # Uncomment and update pr number to use feature branch EPS version
            #- EPS_URL=https://internal-dev-sandbox.api.service.nhs.uk/electronic-prescriptions-pr-123/FHIR/R4
            # Uncomment to use EPS Integration environment
            #- EPS_URL=https://int.api.service.nhs.uk/electronic-prescriptions/FHIR/R4
        ports:
            - "9011:9001"
