version: '3'
services:
  eps-api-tool:
    image: 'eps-api-tool-local'
    build:
        context: .
        dockerfile: Dockerfile-Site
    environment:
        - PYTHONUNBUFFERED=1
        - FLASK_ENV=development
        - FLASK_RUN_PORT=9000
        - DEV_MODE=True
        - ENVIRONMENT=internal-dev-sandbox
        - SESSION_TOKEN_ENCRYPTION_KEY=ZmDfcTF7_60GrrY167zsiPd67pEvs0aGOv2oasOM1Pg=
        - REDIS_URL=redis://eps-api-tool-store:6379
        - PUBLIC_APIGEE_URL=http://localhost:9000
        - APIGEE_DOMAIN_NAME=internal-dev-sandbox.api.service.nhs.uk
    ports:
        - "9000:9000"
  eps-api-tool-store:
    build:
        context: .
        dockerfile: Dockerfile-Store
    environment:
      - HEALTHCHECK_INTERNAL_PORT=9001
    ports:
      - "6379:9001"
    expose:
      - "6379"
