AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  FHIR Prescribing and Dispensing with mTLS

Parameters:
  EnableMutualTLS:
    Type: String

  TruststoreBucketName:
    Type: String
    Default: none

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

  LogRetentionInDays:
    Type: Number
    Default: 30
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1096
      - 1827
      - 2192
      - 2557
      - 2922
      - 3288
      - 3653

Resources:
  LoadBalancers:
    Type: AWS::Serverless::Application
    Properties:
      Location: load_balancer/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableMutualTLS: !Ref EnableMutualTLS
        TruststoreBucketName: !Ref TruststoreBucketName
        TruststoreVersion: !Ref TruststoreVersion
        TruststoreFile: !Ref TruststoreFile
        VersionNumber: !Ref VersionNumber
        CommitId: !Ref CommitId

Outputs:
  LoadBalancerEndpoint:
    Description: Load Balancer Endpoint
    Value: !GetAtt LoadBalancers.Outputs.Endpoint
