AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  FHIR Prescribing and Dispensing with mTLS

Parameters:
  EnableMutualTLS:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

Resources:
  LoadBalancers:
    Type: AWS::Serverless::Application
    Properties:
      Location: load_balancer/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableMutualTLS: !Ref EnableMutualTLS
        TruststoreVersion: !Ref TruststoreVersion
        TruststoreFile: !Ref TruststoreFile
        VersionNumber: !Ref VersionNumber
        CommitId: !Ref CommitId

Outputs:
  LoadBalancerEndpoint:
    Description: Load Balancer Endpoint
    Value: !GetAtt LoadBalancers.Outputs.Endpoint
