AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  FHIR Prescribing and Dispensing with mTLS

Parameters:
  EnableMutualTLS:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

  HostedZoneName:
    Type: String
    Default: "eps-route53-resources:EPS-domain"

  ZoneIDExport:
    Type: String
    Default: "eps-route53-resources:EPS-ZoneID"

Resources:
  LoadBalancerResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: load_balancer/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableMutualTLS: !Ref EnableMutualTLS
        TruststoreVersion: !Ref TruststoreVersion
        TruststoreFile: !Ref TruststoreFile
        VPC: !ImportValue DefaultVPCId
        SubnetA: !ImportValue vpc-resources:PrivateSubnetA
        SubnetB: !ImportValue vpc-resources:PrivateSubnetB
        SubnetC: !ImportValue vpc-resources:PrivateSubnetC
        HostedZoneName: !Ref HostedZoneName
        ZoneIDExport: !Ref ZoneIDExport
        VersionNumber: !Ref VersionNumber
        CommitId: !Ref CommitId

Outputs:
  LoadBalancerEndpoint:
    Description: Load Balancer Endpoint
    Value: !GetAtt LoadBalancerResources.Outputs.Endpoint
