AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  FHIR Prescribing and Dispensing with mTLS

Parameters:
  EnableMutualTLS:
    Type: String

  TruststoreBucketName:
    Type: String
    Default: none

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

Resources:
  LoadBalancers:
    Type: AWS::Serverless::Application
    Properties:
      Location: load_balancer/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableMutualTLS: !Ref EnableMutualTLS
        TruststoreBucketName: !Ref TruststoreBucketName
        TruststoreVersion: !Ref TruststoreVersion
        TruststoreFile: !Ref TruststoreFile
        VersionNumber: !Ref VersionNumber
        CommitId: !Ref CommitId

Outputs:
  LoadBalancerEndpoint:
    Description: Load Balancer Endpoint
    Value: !GetAtt LoadBalancers.Outputs.Endpoint

  SpinePrivateKeyARN:
    Description: ARN of the Spine Private Key
    Value: !ImportValue account-resources:SpinePrivateKey

  SpinePublicCertificateARN:
    Description: ARN of the Spine Public Certificate
    Value: !ImportValue account-resources:SpinePublicCertificate

  SpineCAChainARN:
    Description: ARN of the Spine CA Chain
    Value: !ImportValue account-resources:SpineCAChain

  HCSpinePrivateKeyARN:
    Description: ARN of the Hardcoded Spine Private Key
    Value: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:SpinePublicCertificate-Mt3qmTweyaIJ-ZwxcSb"

  HCSpinePublicCertificateARN:
    Description: ARN of the Hardcoded Spine Public Certificate
    Value: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:SpinePrivateKey-3bPxarwh2ouJ-YAl8Hj"

  HCSpineCAChainARN:
    Description: ARN of the Hardcoded Spine CA Chain
    Value: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:SpineCAChain-8wB0EFsRBYUM-dsPrHf"
