AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  FHIR Prescribing and Dispensing with mTLS

Parameters:
  EnableMutualTLS:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

  TruststoreVersion:
    Type: String
    Default: none

  TruststoreFile:
    Type: String
    Default: none

  VersionNumber:
    Type: String
    Default: "xxx"

  CommitId:
    Type: String
    Default: "xxx"

  CertificateArn:
    Type: String
    Description: ARN of the ACM certificate for the load balancer

  VPC:
    Type: AWS::EC2::VPC::Id

  HostedZoneName:
    Type: String
    Default: company.com

  Subdomain:
    Type: String
    Default: myservice

Resources:
  LoadBalancerResources:
    Type: AWS::Serverless::Application
    Properties:
      Location: load_balancer/main.yaml
      Parameters:
        StackName: !Ref AWS::StackName
        EnableMutualTLS: !Ref EnableMutualTLS
        TruststoreVersion: !Ref TruststoreVersion
        TruststoreFile: !Ref TruststoreFile
        CertificateArn: !Ref CertificateArn
        VPC: !Ref VPC
        SubnetA: !ImportValue vpc-resources:PrivateSubnetA
        SubnetB: !ImportValue vpc-resources:PrivateSubnetB
        SubnetC: !ImportValue vpc-resources:PrivateSubnetC
        HostedZoneName: !Ref HostedZoneName
        Subdomain: !Ref Subdomain
        VersionNumber: !Ref VersionNumber
        CommitId: !Ref CommitId

Outputs:
  LoadBalancerEndpoint:
    Description: Load Balancer Endpoint
    Value: !GetAtt LoadBalancerResources.Outputs.Endpoint
