AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  prescription status update api sandbox template

Resources:
  # Placeholder - Remove once real resources are added
  NullResource:
    Type: Custom:NullResource
    Condition: Never
