type: object
description: A container for Parameters
required:
  - resourceType
  - parameter
properties:
  resourceType:
    type: string
    description: FHIR Resource type.
    enum:
      - "Parameters"
    example: "Parameters"
  parameter:
    type: array
    description: A collection of parameters
    items:
      $ref: "Parameter.yaml"
