version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/specification"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
  - package_manager: "javascript"
    directory: "/coordinator"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
  - package_manager: "javascript"
    directory: "/packages/e2e-tests"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "security:patch"
