name: "$(SourceBranchName)+$(BuildID)"

trigger:
  branches:
    include:
      - tags/refs/v*
  tags:
    include:
      - v*

pr:
  branches:
    include: ['*']

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital

variables:
  - template: project.yml

extends:
  template: azure/common/apigee-build.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    cache_steps:
      # Replace all eps artifacts with eps-api-tool artifacts by
      #   - Deleting eps artifacts
      #   - Moving eps-api-tool artifacts from tool/ directory to root directory
      #   - Copying examples project resources into tool
      # Having root directory CI/CD files is required by platforms
      - task: DeleteFiles@1
        displayName: 'Deleting eps artifacts'
        inputs:
          sourceFolder: "${{ variables.service_name }}"
          contents: |
            !{tool,examples}
      - bash: |
          set -euo pipefail
          ls -lah
          rsync -vua --delete-after tool/ .
          rsync -vua --delete-after examples client/static/
          ls -lah
          ls -lah client/static/examples
        workingDirectory: "${{ variables.service_name }}"
        displayName: Prepare eps-api-tool
    test_steps:
      - bash: "make test"
        displayName: Run Quality Checks
        workingDirectory: "${{ variables.service_name }}"
