name: Build and Upload Docker Image

on:
  pull_request:
    branches: [docker-test]

env:
  ECR_REPOSITORY: FHIR_API_repo
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_upload_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        id: build-image
        run: |
           docker build -t "${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" .

      - name: Upload Docker image as artifact
        uses: ishworkh/container-image-artifact-upload@v1.1.1
        with:
          image: "${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
