name: PR

on: pull_request

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      # dependencies can be removed once self-hosted runners are being used #
      # dependencies #
      - uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'
      - uses: actions/setup-python@v1
      - run: |
          pip install -U pip
          pip install poetry
      # /dependencies #

      - uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - run: make install-all
      - run: make test-coordinator
