name: package code and api

on:
  workflow_call:
    inputs:
      APIGEE_ENVIRONMENT:
        required: true
        type: string
      VERSION_NUMBER:
        required: true
        type: string
    secrets:
      API_CLIENT_ID:
        required: true
      API_CLIENT_SECRET:
        required: true
      SIGNING_PRIVATE_KEY:
        required: true
      SIGNING_CERT:
        required: true
jobs:
  run_pact_tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      # using git commit sha for version of action to ensure we have stable version
      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.11.3
  
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-

      - name: Install asdf dependencies in .tool-versions
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6
        with:
          asdf_branch: v0.11.3
        env:
          PYTHON_CONFIGURE_OPTS: --enable-shared
      
      - name: Run make install
        run: |
          make install

      - name: Prepare pacts
        shell: bash
        run: |
          APIGEE_ACCESS_TOKEN=dummy_token
          export APIGEE_ACCESS_TOKEN
          mkdir -p .secrets
          echo "${SIGNING_PRIVATE_KEY}" > .secrets/private.key
          echo "${SIGNING_CERT}" > .secrets/cert.crt
          SIGNING_PRIVATE_KEY_PATH=${PWD}/.secrets/private.key
          SIGNING_CERT_PATH=${PWD}/.secrets/cert.crt
          export SIGNING_PRIVATE_KEY_PATH
          export SIGNING_CERT_PATH

          echo "SERVICE_ARTIFACT_NAME: ${SERVICE_ARTIFACT_NAME}"
          echo "SERVICE_BASE_PATH: ${SERVICE_BASE_PATH}"
          echo "APIGEE_ENVIRONMENT: ${APIGEE_ENVIRONMENT}"
          echo "PACT_VERSION: ${PACT_VERSION}"
          echo "PACT_PROVIDER_URL: ${PACT_PROVIDER_URL}"
          echo "PACT_CONSUMER: ${PACT_CONSUMER}"
          echo "PACT_PROVIDER: ${PACT_PROVIDER}"
          echo "SIGNING_PRIVATE_KEY_PATH: ${SIGNING_PRIVATE_KEY_PATH}"
          echo "SIGNING_CERT_PATH: ${SIGNING_CERT_PATH}"
          echo "API_PRODUCT: ${API_PRODUCT}"
          echo "API_CLIENT_ID: HIDDEN"
          echo "API_CLIENT_SECRET: HIDDEN"
          echo "APIGEE_ACCESS_TOKEN: HIDDEN"

          make create-proxygen-pacts
        env:
          SERVICE_ARTIFACT_NAME: electronic-prescription-service-api-prescribing-pacts
          SERVICE_BASE_PATH: fhir-prescribing-${{ inputs.VERSION_NUMBER }}
          APIGEE_ENVIRONMENT: ${{ inputs.APIGEE_ENVIRONMENT }}
          PACT_VERSION: electronic-prescriptions-${{ inputs.VERSION_NUMBER }}
          PACT_PROVIDER_URL: https://internal-dev.api.service.nhs.uk/fhir-prescribing-${{ inputs.VERSION_NUMBER }}
          PACT_CONSUMER: nhsd-apim-eps-test-client
          PACT_PROVIDER: nhsd-apim-eps
          API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
          API_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
          API_PRODUCT: proxygen
          SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          SIGNING_CERT:  ${{ secrets.SIGNING_CERT }}


      - name: Verify pacts
        shell: bash
        run: |
          PACT_PROVIDER_PRESCRIBING_URL=$(echo "$PACT_PROVIDER_PRESCRIBING_URL" | tr '[:upper:]' '[:lower:]')
          PACT_PROVIDER_DISPENSING_URL=$(echo "$PACT_PROVIDER_DISPENSING_URL" | tr '[:upper:]' '[:lower:]')
          export PACT_PROVIDER_URL
          echo "SERVICE_ARTIFACT_NAME: ${SERVICE_ARTIFACT_NAME}"
          echo "SERVICE_BASE_PATH: ${SERVICE_BASE_PATH}"
          echo "APIGEE_ENVIRONMENT: ${APIGEE_ENVIRONMENT}"
          echo "PACT_VERSION: ${PACT_VERSION}"
          echo "PACT_PROVIDER_URL: ${PACT_PROVIDER_URL}"
          echo "PACT_CONSUMER: ${PACT_CONSUMER}"
          echo "PACT_PROVIDER: ${PACT_PROVIDER}"
          echo "API_PRODUCT: ${API_PRODUCT}"

          make verify-pacts
        env:
          SERVICE_ARTIFACT_NAME: electronic-prescription-service-api-prescribing-pacts
          SERVICE_BASE_PATH: fhir-prescribing-${{ inputs.VERSION_NUMBER }}
          APIGEE_ENVIRONMENT: ${{ inputs.APIGEE_ENVIRONMENT }}
          PACT_VERSION: electronic-prescriptions-${{ inputs.VERSION_NUMBER }}
          PACT_PROVIDER_PRESCRIBING_URL: https://internal-dev.api.service.nhs.uk/fhir-prescribing-${{ inputs.VERSION_NUMBER }}
          PACT_PROVIDER_DISPENSING_URL: https://internal-dev.api.service.nhs.uk/fhir-dispensing-${{ inputs.VERSION_NUMBER }}
          PACT_CONSUMER: eps-test-client
          PACT_PROVIDER: eps
          API_PRODUCT: proxygen
          API_CLIENT_ID: ${{ secrets.API_CLIENT_ID }}
          API_CLIENT_SECRET: ${{ secrets.API_CLIENT_SECRET }}
